print("Enter your question (or type 'exit' to stop):")
question = input("Enter question: ")
a = input("Choice a: ")
b = input("Choice b: ")
c = input("Choice c: ")
d = input("Choice d: ")
answer = input("Correct answer (a/b/c/d): ")

print("Question:", question)
print("a)", a)
print("b)", b)
print("c)", c)
print("d)", d)
print("Answer:", answer)

with open("quiz.txt", "w") as file:
    file.write("Question: " + question + "\n")
    file.write("a) " + a + "\n")
    file.write("b) " + b + "\n")
    file.write("c) " + c + "\n")
    file.write("d) " + d + "\n")
    file.write("Answer: " + answer + "\n")
    file.write("---\n")
